name: embedme verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  embedme:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3
        - name: checkout
          uses: mikeal/npx@1.0.0
        - name: Run embedme --verify
          run: npx embedme --verify README.md
          